# Generated by Django 5.1.7 on 2025-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_errorlog_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="exception_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="exception_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="traceback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
